### PR TITLE
chore: remove CosmWasm/wasmd duplication

### PR DESCRIPTION
**Pull request by tclairet**
* forked [CosmWasm/wasmd](https://github.com/CosmWasm/wasmd) to [tclairet/wasmd](https://github.com/tclairet/wasmd) and made one [commit](https://github.com/tclairet/wasmd/commit/142933820aa008f37ddafcbc994bf8dbc15dfe25) to make it work with a struct defined here. This way all change are easily tracked and not mixed with our core updates.
* create a wrapper around `x/wasm/keeper/Keeper` so that we reuse 99% of `CosmWasm/wasmd` code
* delete old the redundant code
* have look at the [commit on the wasmd fork too](https://github.com/tclairet/wasmd/commit/142933820aa008f37ddafcbc994bf8dbc15dfe25)
* my fork [tclairet/wasmd](https://github.com/tclairet/wasmd) will need to be on qredo repo if that pr is accepeted. I don't have have the right to do that myself

### CODE REVIEW

**Review by sashaduke — CHANGES_REQUESTED** [review]
Interoperability features implemented in the following files need to be carried over to the forked repo:
`x/wasm/keeper/query_plugins.go`
`x/wasm/keeper/handler_plugin.go`

I think those are the only files but it wouldn't hurt to do a diff check between our x/wasm and the vanilla one just to be sure

**Comment by tclairet** [comment]
It's already done 
[blockchain/x/wasm/keeper/handler_plugin.go](https://github.com/qredo/fusionchain/pull/94/files#diff-40daa7f19f1c4f0b631aafbac51e7242e0b610c79b0c0ed0105318ad23277d86)
[blockchain/x/wasm/keeper/query_plugins.go](https://github.com/qredo/fusionchain/pull/94/files#diff-605dadd278b772ba26f903f1d2df54143cb401aa523212e30e50625599bd2c61)
[blockchain/x/wasm/keeper/keeper_cgo.go](https://github.com/qredo/fusionchain/pull/94/files#diff-d24688afe9c40ce09bb5d68995639f063735680c13fbb1fdb0e4c26ea77735af)

**Review by sashaduke — APPROVED** [review]
mb, I was looking in your forked repo for those files

**Review by Lazar955 — CHANGES_REQUESTED** [review]
Can you fork wasmd under qredo, I think this is much better than being under your personal gh. And of course you need to do a SNOW ticket

**Comment by tclairet** [comment]
> mb, I was looking in your forked repo for those files

Oh yeah, I think it's a better to keep those changes close to our codebase. That way the fork can be easily rebased on new version without much modifications, the fork doesn't rely in anyway on the qredochain and we can expand the api of our wasm keeper without updating the fork.

**Review by Marty-Q — APPROVED** [review]

**Pull request merged**
