### PR TITLE
fix(docker): support Mac OS and Linux using build args

### PR DESCRIPTION
**Pull request by ATMackay**

### CODE REVIEW

**Review by tclairet — APPROVED** [review]

**Review by Marty-Q — APPROVED** [review]

**Comment by Pitasi** [comment]
What's being added by this PR apart from logging "architecture: ${arch}"?

**Comment by ATMackay** [comment]
> What's being added by this PR apart from logging "architecture: ${arch}"?

The var is used as a build argument in the various Docker files.

**Comment by Marty-Q** [comment]
It helps building the docker images on Mac and Linux and fixes a dependency

**Comment by Pitasi** [comment]
> The var is used as a build argument in the various Docker files

yes but, they only print the var value? Unless I'm missing some knowledge about dockerfiles 😛

**Comment by Pitasi** [comment]
for example I see a `--platform=linux/amd64` in the Dockerfile-package (now renamed to Dockerfile-fusion-stack)

**Comment by ATMackay** [comment]
> > The var is used as a build argument in the various Docker files
> 
> yes but, they only print the var value? Unless I'm missing some knowledge about dockerfiles 😛

see my comment in the file.

**Pull request merged**
